<nav class="sidebar">
    <ul>
        <li><a class="add" href="Dispatcher?controllerAction=GestioneManagement.insSpettacoloView"><span>Aggiungi spettacolo</span></a></li>
        <li><a class="add" href="Dispatcher?controllerAction=GestioneManagement.insCouponView"><span>Aggiungi coupon</span></a></li>
        <li><a class="view" href="Dispatcher?controllerAction=GestioneManagement.bigliettiView"><span>Visualizza biglietti</span></a></li>
        <li><a class="view" href="Dispatcher?controllerAction=GestioneManagement.couponView"><span>Visualizza coupon</span></a></li>
    </ul>
</nav>