<nav class="sidebar">
    <ul>
        <li><a class="add" href="Dispatcher?controllerAction=SpettacoliManagement.insView"><span>Aggiungi spettacolo</span></a></li>
        <li><a class="add" href="Dispatcher?controllerAction=CouponManagement.insView"><span>Aggiungi coupon</span></a></li>
        <li><a class="view" href="Dispatcher?controllerAction=BigliettiManagement.view"><span>Visualizza biglietti</span></a></li>
        <li><a class="view" href="Dispatcher?controllerAction=CouponManagement.view"><span>Visualizza coupon</span></a></li>
    </ul>
</nav>